

# This file was *autogenerated* from the file ../polytest.sage
from sage.all_cmdline import *   # import sage library

_sage_const_7 = Integer(7); _sage_const_3 = Integer(3); _sage_const_2 = Integer(2); _sage_const_5 = Integer(5); _sage_const_4 = Integer(4); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0)
R = PolynomialRing(Zmod(_sage_const_7 ), names=('t',)); (t,) = R._first_ngens(1)
m = t ** _sage_const_3  + t ** _sage_const_2  
a = _sage_const_2  * t ** _sage_const_2  + _sage_const_5 
n = t ** _sage_const_4  + _sage_const_1 

s = m * a % n


def exgcd(a,b):
    if(b == _sage_const_0 *t):
        return _sage_const_1 ,_sage_const_0 ,a
    else:
        x,y,q = exgcd(b,a%b)
        x,y = y, (x - (a // b) * y)
        return x,y,q
a = t ** _sage_const_5  
e = _sage_const_1  + t
n = t**_sage_const_4  + _sage_const_1 
print(a % n)
# a_inv = exgcd(a,n)[0]

# print(a_inv)

